name: Java CI with Gradle

on:
  push:
    branches:
      - release

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew

      - name: create resources folder if not exists
        run: mkdir -p src/main/resources

      - name: set up application.properties
        run: echo "${{ secrets.APPLICATION }}" > src/main/resources/application.properties

      - name: set up .env file
        run: echo "${{ secrets.ENV }}" > .env

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean bootJar

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker image build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/classfit-server .

      - name: Docker Hub push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/classfit-server:latest

  deploy-to-server:
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:

      - name: Run Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ita
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          envs: COMPOSE
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker rm $(docker ps -a -q)
            docker rmi ${{ secrets.USERNAME }}/classfit-server:latest
            docker pull ${{ secrets.USERNAME }}/classfit-server:latest
            docker-compose up -d